[project]
name = "dialog"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "rasa==3.6.21",
    "aiohttp>=3.9",
]

[dependency-groups]
dev = [
    "black==22.12.0"
]